### ISSUE TITLE
Group indicators

### ISSUE THREAD

**Issue by olafveerman** [climatescope/cs-datapipeline#12]
Allow indicators to be grouped.

![image](https://user-images.githubusercontent.com/751330/48009523-e6dc5000-e0e9-11e8-8122-1aaf55defa57.png)

The `charts.csv` will be structured this way. The `indicatorId` refers to other rows in the `charts.csv` by their ID.

| id | indicatorId | name | type | description |
| --- | --- | --- | --- | --- |
| averageVAT | largeVAT\|smallVAT | Average VAT paid by renewables | group | What is the average level of VAT for components needed to build a wind project?|
| largeVAT | VAT - Large scale renewables | Large scale renewables | absolute | |
| smallVAT | VAT - Small scale renewables | Small scale renewables | absolute | | 

The output data will be structured:

``` json
{
  "id": "averageVAT",
  "description": "What is the average level of VAT for components needed to build a wind project?",
  "data": [
    {
      "name": "Large scale renewables",
      "value": 0.23,
      "year": 2017
    },
    {
      "name": "Small scale renewables",
      "value": 0.20,
      "year": 2017
    }
  ]
}
```

**Comment by olafveerman** [comment]
Further thoughts @danielfdsilva ?

**Comment by danielfdsilva** [comment]
Perfect
