### ISSUE TITLE
Add percentage chart type

### ISSUE THREAD

**Issue by danielfdsilva** [climatescope/cs-datapipeline#23]
Charts like `largeVAT` and `smallVAT`, among others, would be better with a `percentage` type. Only percentages can be visualized with this type of chart:
![image](https://user-images.githubusercontent.com/1090606/48136520-c520cb80-e297-11e8-9dfb-03695c1f2d37.png)

**Comment by danielfdsilva** [comment]
@olafveerman is this possible?

**Comment by olafveerman** [comment]
The unit will be part of chartMeta, which we can use to format the value.
I'll close this issue, we can revisit if a specific chart type is necessary.
