### ISSUE TITLE
Invalid value for 'curtailmentRisk'

### ISSUE THREAD

**Issue by danielfdsilva** [climatescope/cs-datapipeline#29]
The chart `curtailmentRisk` has the following options:
```
{
  "id": "2",
  "label": "Yes"
},
{
  "id": "1",
  "label": "Somewhat"
},
{
  "id": "0",
  "label": "No"
}
```

but some geographies show `0.5`. For example `Chile` and `Central African Republic`

**Comment by olafveerman** [comment]
Added a placeholder label for `0.5`. Keeping this issue open until we get feedback on how to account for this.
