### ISSUE TITLE
Confirm average retail power price data

### ISSUE THREAD

**Issue by danielfdsilva** [climatescope/cs-datapipeline#37]
> Could you confirm what data is used for average retail power price? At the moment the copy says "Average residential electricity in the country" and shows wrong data. It should say "Average retail electricity price" and be an average of retail prices only / not include the wholesale price value.

**Comment by olafveerman** [comment]
Capturing notes from email:

> For the Average retail electricity price we're calculating the average from these 3 indicators.
> - Average residential electricity prices
> - Average commercial electricity prices
> - Average industrial electricity prices

Dario:

> Great. So just call it "Average retail electricity price".

No further action required.
