### ISSUE TITLE
Remove off grid indicators from on grid countries

### ISSUE THREAD

**Issue by danielfdsilva** [climatescope/cs-datapipeline#38]
> Off-grid indicators should not appear on the on-grid country profiles. If they cannot be removed the message should read "Only applicable to off-grid countries.

**Comment by olafveerman** [comment]
A workaround is in place in the frontend, and charts are excluded based on ID.

Instead, add a column `applicable-grid` to the CSV with the chart definition with one of the following values:

`on`, `off`, `both`

Currently, only `kerosene and diesel` is available on off-grid only. The rest on `both`
